#ifndef OPERATIONNAME_H
#define OPERATIONNAME_H
enum OperationName
{
    MONOCHROME, CHANGECOLOUR, CHANGECOLOURIFNOT, LIMITCOLOUR, CROP, CROPEDGES, ADDIMAGETO, ADDBORDER, ADDINNERBORDER,
    COLOURISE
};

#endif // OPERATIONNAME_H

